name: Build Windows 32-bit EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install MinGW
        run: |
          choco install mingw -y
          $env:PATH += ";C:\tools\mingw64\bin"

      - name: Compile EXE
        run: |
          gcc main.c -o main.exe -m32 -mwindows

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: main.exe
